In [2]:
import numpy as np

## Datatypes and Attributes

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.3]])

a3 = np.array([[[1, 2 ,3],
                [4, 5, 6,],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14 ,15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.3]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Create a DataFrame from a numpy array

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.3


# Create Numpy Arraysf

In [14]:
# Array with Ones
ones = np.ones(shape=(3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(1, 3, size=(3, 4))
random_array

array([[1, 1, 1, 1],
       [2, 1, 1, 2],
       [2, 2, 1, 2]], dtype=int32)

In [21]:
random_array.size

12

In [22]:
random_array.shape

(3, 4)

In [24]:
random_array_2 = np.random.random((3, 4))
random_array_2

array([[0.4705136 , 0.15302857, 0.55890477, 0.93691223],
       [0.66356653, 0.91918649, 0.25019985, 0.30565308],
       [0.8056732 , 0.98427813, 0.07252025, 0.89834768]])

In [36]:
random_array_3 = np.random.rand(3, 4)
random_array_3

array([[0.46147936, 0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395]])

In [40]:
# Pseudo random numbers
np.random.seed(seed=9)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 6, 8],
       [6, 1, 6],
       [4, 8, 1],
       [8, 5, 1],
       [0, 8, 8]], dtype=int32)